server:
  host: ${RESTFUL_HOST}
  port: ${RESTFUL_PORT}
  grpcHost: ${GRPC_HOST}
  grpcPort: ${GRPC_PORT}
  debug: ${DEBUG}
  readTimeout: 5
  writeTimeout: 5
  contextTimeout: 5
  rateLimitPerSec: 10
  timezone: UTC
  accessJwtSecret: ${ACCESS_JWT_SECRET}
  accessJwtExpireTime: ${ACCESS_JWT_EXPIRE_TIME}


database:
  adapter: "postgres"
  host: ${POSTGRES_HOST}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  db: ${POSTGRES_DATABASE}
  port: 5432
  maxConns: 20
  maxLiftimeConns: 7200

cassandra:
  host: ${CASSANDRA_HOST}
  keyspace: ${CASSANDRA_KEYSPACE}
  consistency: "quorum"
  protoVersion: 4
  username: "user"
  password: "password"

logger:
  development: false
  disableCaller: false
  disableStacktrace: false
  encoding: json
  level: info
  filename: assets/access.log
  fileMaxSize: 10
  fileMaxAge: 30
  fileMaxBackups: 5
  fileIsCompress: false

jaeger:
  host: ${JAEGER_HOST}
  port: 14268
  serviceName: chat-app
  logSpans: true

metric:
  url: "localhost:7070"
  serviceName: chat-app


kafka:
  brokers: ${KAFKA_BROKER}
  groupID: "customer-1"
  topics:
    user_email: 
      name: user_email
      partitions: 1
      replicationFactor: 1